spring:
  server:
    port: '8762'
    enableSelfPreservation: true
    renewalPercentThreshold: 0.33


  eureka:
    client:
      registerWithEureka: true
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://localhost:8762/eureka
